upstream auth_ccolon {
    zone ccolon_mobile 64k;
    keepalive 32;
    server host.containers.internal:3100 max_fails=3 fail_timeout=30s;
}

upstream atm_api {
    zone atm_api 64k;
    keepalive 32;
    server 10.10.10.191:4000 max_fails=3 fail_timeout=30s;
}

upstream atm_ws {
    zone atm_ws 64k;
    keepalive 32;
    server 10.10.10.191:4001 max_fails=3 fail_timeout=30s;
}
