services:
  waf:
    image: nginx-waf:1.28.2-modsec3.0.14-crs4.23.0
    container_name: waf
    ports:
      - "8080:80"
    environment:
      ENABLE_HTTPS: "0"
      AUTO_RELOAD_CERTS: "1"
    volumes:
      - ./conf.d/upstreams.conf:/etc/nginx/conf.d/upstreams.conf:ro
      - ./sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
