server {
    listen 80;
    server_name 10.10.10.115 127.0.0.1 localhost;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    proxy_hide_header Server;
    proxy_hide_header X-Powered-By;

    location /__rid_debug {
        add_header X-Debug-Incoming-Request-Id "$http_x_request_id" always;
        add_header X-Debug-Generated-Request-Id "$request_id" always;
        add_header X-Debug-Effective-Request-Id "$effective_request_id" always;
        return 204;
    }

    location /desarrollo/ {
        proxy_pass http://auth_ccolon/;

        include /etc/nginx/conf.d/proxy_common.conf;
        include /etc/nginx/conf.d/proxy_http.conf;

        proxy_buffering off;
        proxy_cache off;
    }

    location /atm/api/ {
        proxy_pass http://atm_api/;

        include /etc/nginx/conf.d/proxy_common.conf;
        include /etc/nginx/conf.d/proxy_http.conf;

        proxy_buffering off;
        proxy_cache off;
    }

    location /atm/ws/ {
        proxy_pass http://atm_ws/;

        include /etc/nginx/conf.d/proxy_common.conf;
        include /etc/nginx/conf.d/proxy_ws.conf;

        proxy_buffering off;
        proxy_cache off;
    }
}
